 
name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Add your steps here
      
      - name: Build and test
        run: |
          echo "Building and testing..."
          # Add your build and test commands here
          
      - name: Deploy
        run: |
          echo "Deploying..."
          # Add your deployment commands here